#!/usr/bin/env python3
"""Regenerate every index in this repo from its single source of truth.

Source of truth:
  - plugins/*/skills/*/SKILL.md   (YAML frontmatter: name, description)
  - agents/*.md                   (YAML frontmatter: name, description)
  - marketplace.json              only for: owner, metadata, per-plugin category/tags

Generated / synced (never edit by hand):
  - plugins/*/.claude-plugin/plugin.json  "description" synced from SKILL.md frontmatter
  - .claude-plugin/marketplace.json       "plugins" array rebuilt (category/tags preserved)
  - catalog.json                          machine-readable inventory
  - llms.txt                              LLM-facing index (llmstxt.org format)
  - README.md                             only the block between CATALOG markers

Usage: python3 scripts/build_index.py
Stdlib only — no dependencies. Idempotent: a second run changes nothing.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG_START = "<!-- CATALOG:START — generated by scripts/build_index.py; do not edit by hand -->"
CATALOG_END = "<!-- CATALOG:END -->"
FALLBACK_REPO = "https://github.com/Fernando-Kalid/toolkit"
BRANCH = "main"
CATEGORY_TITLES = {
    "decks": "Branded deck generators",
    "marketing": "Marketing & comms studio",
}


def repo_url() -> str:
    """https URL of origin, without trailing .git."""
    try:
        url = subprocess.run(
            ["git", "-C", str(ROOT), "remote", "get-url", "origin"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except Exception:
        return FALLBACK_REPO
    url = re.sub(r"^git@github\.com:", "https://github.com/", url)
    return re.sub(r"\.git$", "", url) or FALLBACK_REPO


def parse_frontmatter(text: str) -> dict:
    """Minimal YAML frontmatter parser: top-level scalars and >-/| block scalars."""
    if not text.startswith("---"):
        return {}
    lines = text.split("\n")
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        return {}
    fm, i = {}, 1
    while i < end:
        m = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", lines[i])
        if not m:
            i += 1
            continue
        key, val = m.group(1), m.group(2).strip()
        if val in (">", ">-", ">+", "|", "|-", "|+"):
            block = []
            i += 1
            while i < end and (lines[i].startswith("  ") or lines[i].strip() == ""):
                block.append(lines[i].strip())
                i += 1
            joiner = " " if val.startswith(">") else "\n"
            fm[key] = joiner.join(b for b in block if b)
            continue
        if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
            val = val[1:-1]
        fm[key] = val
        i += 1
    return fm


def short_desc(desc: str, limit: int = 180) -> str:
    """First sentence when reasonable, else a word-boundary truncation."""
    desc = " ".join(desc.split())
    m = re.search(r"(?<=[a-z)\]])\.\s", desc)
    if m and 60 <= m.end() - 1 <= 220:
        return desc[: m.end() - 1].strip()
    if len(desc) <= limit:
        return desc
    return desc[:limit].rsplit(" ", 1)[0].rstrip(",;:") + "…"


def dir_stats(path: Path) -> tuple[int, int]:
    files = [f for f in path.rglob("*") if f.is_file()]
    return len(files), round(sum(f.stat().st_size for f in files) / 1024)


def write_json(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def sync_manifests() -> dict:
    """Sync plugin.json descriptions and the marketplace plugins array from
    SKILL.md frontmatter. Returns the up-to-date marketplace dict."""
    mp_path = ROOT / ".claude-plugin" / "marketplace.json"
    marketplace = json.loads(mp_path.read_text())
    old_entries = {p["name"]: p for p in marketplace.get("plugins", [])}

    entries = []
    for plugin_dir in sorted((ROOT / "plugins").iterdir()):
        pj_path = plugin_dir / ".claude-plugin" / "plugin.json"
        if not pj_path.exists():
            continue
        pj = json.loads(pj_path.read_text())
        skill_mds = sorted((plugin_dir / "skills").glob("*/SKILL.md"))
        # Default layout is one skill per plugin: description comes from the skill.
        if len(skill_mds) == 1:
            fm = parse_frontmatter(skill_mds[0].read_text())
            desired = short_desc(fm.get("description", ""), limit=240)
            if pj.get("description") != desired:
                pj["description"] = desired
                write_json(pj_path, pj)
        old = old_entries.get(pj["name"], {})
        entries.append({
            "name": pj["name"],
            "source": f"./plugins/{plugin_dir.name}",
            "description": pj.get("description", ""),
            "version": pj.get("version", "0.0.0"),
            "author": {"name": marketplace["owner"]["name"]},
            "category": old.get("category", ""),
            "tags": old.get("tags", []),
        })

    if marketplace.get("plugins") != entries:
        marketplace["plugins"] = entries
        write_json(mp_path, marketplace)
    return marketplace


def collect(repo: str, marketplace: dict) -> dict:
    raw = f"{repo.replace('github.com', 'raw.githubusercontent.com')}/{BRANCH}"
    mp_meta = {p["name"]: p for p in marketplace.get("plugins", [])}

    plugins = []
    for plugin_dir in sorted((ROOT / "plugins").iterdir()):
        pj_path = plugin_dir / ".claude-plugin" / "plugin.json"
        if not pj_path.exists():
            continue
        pj = json.loads(pj_path.read_text())
        skills = []
        for skill_dir in sorted((plugin_dir / "skills").iterdir()):
            skill_md = skill_dir / "SKILL.md"
            if not skill_md.exists():
                continue
            fm = parse_frontmatter(skill_md.read_text())
            if not fm.get("name") or not fm.get("description"):
                sys.exit(f"ERROR: {skill_md} is missing name/description frontmatter")
            if fm["name"] != skill_dir.name:
                sys.exit(f"ERROR: {skill_md} frontmatter name '{fm['name']}' != folder '{skill_dir.name}'")
            n_files, kb = dir_stats(skill_dir)
            rel = skill_dir.relative_to(ROOT).as_posix()
            skills.append({
                "name": fm["name"],
                "description": fm["description"],
                "path": rel,
                "skill_md": f"{raw}/{rel}/SKILL.md",
                "files": n_files,
                "size_kb": kb,
            })
        plugins.append({
            "name": pj["name"],
            "description": pj.get("description", ""),
            "version": pj.get("version", "0.0.0"),
            "category": mp_meta.get(pj["name"], {}).get("category", ""),
            "tags": mp_meta.get(pj["name"], {}).get("tags", []),
            "path": plugin_dir.relative_to(ROOT).as_posix(),
            "install": f"/plugin install {pj['name']}@{marketplace['name']}",
            "skills": skills,
        })

    agents = []
    agents_dir = ROOT / "agents"
    if agents_dir.exists():
        for f in sorted(agents_dir.glob("*.md")):
            if f.name.upper() == "README.MD":
                continue
            fm = parse_frontmatter(f.read_text())
            agents.append({
                "name": fm.get("name", f.stem),
                "description": fm.get("description", ""),
                "path": f.relative_to(ROOT).as_posix(),
            })

    def listing(dirname: str) -> list:
        d = ROOT / dirname
        if not d.exists():
            return []
        return [
            {"name": p.name, "path": p.relative_to(ROOT).as_posix()}
            for p in sorted(d.iterdir())
            if not p.name.startswith(".") and p.name.upper() != "README.MD"
        ]

    return {
        "name": marketplace["name"],
        "description": marketplace["metadata"]["description"],
        "repo": repo,
        "owner": marketplace["owner"]["name"],
        "install": {
            "claude_code": [
                f"/plugin marketplace add {repo.removeprefix('https://github.com/')}",
                f"/plugin install <skill>@{marketplace['name']}",
            ],
            "claude_ai": "Download the skill's zip from the latest GitHub release (or run scripts/package_skills.sh), then upload it in Claude settings under Capabilities → Skills.",
            "manual": "Copy any skill folder into ~/.claude/skills/ (personal) or <project>/.claude/skills/ (project).",
        },
        "plugins": plugins,
        "agents": agents,
        "artifacts": listing("artifacts"),
        "styles": listing("styles"),
    }


def by_category(cat: dict) -> list[tuple[str, list]]:
    """Plugins grouped by category, in CATEGORY_TITLES order, extras last."""
    order = list(CATEGORY_TITLES)
    groups: dict[str, list] = {}
    for p in cat["plugins"]:
        groups.setdefault(p["category"] or "other", []).append(p)
    keys = [k for k in order if k in groups] + sorted(k for k in groups if k not in order)
    return [(k, groups[k]) for k in keys]


def write_llms_txt(cat: dict) -> None:
    repo, raw = cat["repo"], f"{cat['repo'].replace('github.com', 'raw.githubusercontent.com')}/{BRANCH}"
    lines = [
        "# FK Toolkit",
        "",
        f"> {cat['description']} Everything here installs into your own Claude account: "
        "via the Claude Code plugin marketplace, a skill zip upload on claude.ai, or a manual copy.",
        "",
        f"Each skill is its own plugin, so users install exactly the skills they pick: "
        f"`{cat['install']['claude_code'][0]}` once, then `{cat['install']['claude_code'][1]}` per skill. "
        "A skill is a folder with a SKILL.md whose YAML frontmatter (name, description) is the canonical metadata.",
        "",
        "## Skills",
        "",
    ]
    for plugin in cat["plugins"]:
        for s in plugin["skills"]:
            lines.append(f"- [{s['name']}]({s['skill_md']}): {short_desc(s['description'])} "
                         f"(category: {plugin['category'] or 'other'}; install: `{plugin['install']}`)")
    if cat["agents"]:
        lines += ["", "## Agents", ""]
        for a in cat["agents"]:
            lines.append(f"- [{a['name']}]({raw}/{a['path']}): {short_desc(a['description'])}")
    lines += [
        "",
        "## Documentation",
        "",
        f"- [README]({raw}/README.md): human-facing overview and catalog",
        f"- [Install guide]({raw}/docs/INSTALL.md): per-surface install instructions (Claude Code, claude.ai, manual, teams)",
        f"- [Maintainer guide]({raw}/CLAUDE.md): repo conventions for humans and agents making changes",
        "",
        "## Machine index",
        "",
        f"- [catalog.json]({raw}/catalog.json): full inventory with complete descriptions, paths, and install commands",
        f"- [marketplace.json]({raw}/.claude-plugin/marketplace.json): Claude Code plugin marketplace manifest",
        "",
    ]
    (ROOT / "llms.txt").write_text("\n".join(lines))


def render_catalog_md(cat: dict) -> str:
    out = [
        f"Every skill installs individually: `{cat['install']['claude_code'][0]}` once, "
        f"then `/plugin install <skill>@{cat['name']}`.",
        "",
    ]
    for key, plugins in by_category(cat):
        out += [f"### {CATEGORY_TITLES.get(key, key.title())}", ""]
        out += ["| Skill | What it does | Size |", "|---|---|---|"]
        for plugin in plugins:
            for s in plugin["skills"]:
                out.append(f"| [{s['name']}]({s['path']}) | {short_desc(s['description'])} | {s['size_kb']} KB |")
        out.append("")
    if cat["agents"]:
        out += ["### Agents", ""]
        for a in cat["agents"]:
            out.append(f"- [{a['name']}]({a['path']}): {short_desc(a['description'])}")
        out.append("")
    return "\n".join(out).rstrip()


def write_readme_block(cat: dict) -> None:
    readme = ROOT / "README.md"
    text = readme.read_text()
    if CATALOG_START not in text or CATALOG_END not in text:
        sys.exit("ERROR: README.md is missing the CATALOG markers")
    pre = text.split(CATALOG_START)[0]
    post = text.split(CATALOG_END)[1]
    readme.write_text(pre + CATALOG_START + "\n\n" + render_catalog_md(cat) + "\n\n" + CATALOG_END + post)


def main() -> None:
    marketplace = sync_manifests()
    cat = collect(repo_url(), marketplace)
    write_json(ROOT / "catalog.json", cat)
    write_llms_txt(cat)
    write_readme_block(cat)
    n_skills = sum(len(p["skills"]) for p in cat["plugins"])
    print(f"OK: indexed {n_skills} skills in {len(cat['plugins'])} plugins, "
          f"{len(cat['agents'])} agents, {len(cat['artifacts'])} artifacts, {len(cat['styles'])} styles")
    print("Synced: plugin.json descriptions, marketplace.json plugins array")
    print("Regenerated: catalog.json, llms.txt, README.md (catalog block)")


if __name__ == "__main__":
    main()
